---
title: "sims"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
data_full <- as.data.table(simulate(3000, censoring = TRUE))
group <- (data_full$W1<=0)
g1 <- sample(which(group), 500, replace = F)
g2 <- sample(which(!group), 1000, replace = F)
data <- data_full[c(g1,g2),]
data$group <- c(rep(1,500), rep(1,1000))
data$weights <-1/ c(rep(500/3000, 500), rep(1000/3000, 1000))
```

```{r}
devtools::load_all()
```

```{r}
data_sim <- as.data.table(simulate(30000, censoring = F))

true <- mean((data_sim$T <= 7)*(data_sim$J >= cutoffs_J)*(data_sim$A >= cutoffs_A))/mean((data_sim$A >= cutoffs_A))
true
hist(data_sim$A)
hist(data_sim$T[data_sim$A<= 0.5])
hist(data_sim$T[data_sim$A>= 0.5])
```

```{r}
 
#remotes::install_github("tlverse/tmle3sim")
#set.seed(1069583)
 estimates<-list()
 outcome <- c()

for(i in 1:100) {
  #try({
  print(i)
  #data <- as.data.table(simulate(2000, censoring = TRUE))
  #data_sim <- as.data.table(simulate(25000, censoring = F))
    data_full <- as.data.table(simulate(3000, censoring = TRUE))
  group <- (data_full$W1<=0)
  g1 <- sample(which(group), 750, replace = F)
  g2 <- sample(which(!group), 1250, replace = F)
  data <- data_full[c(g1,g2),]
  data$group <- c(rep(1,750), rep(0,1250))
  data$weights <-1/ c(rep(750/sum(group), 750), rep(1250/sum(1-group), 1250))
  target_times <- c(7)
  cutoffs_J <- 0.516
  cutoffs_A <- 0.5
  node_list <- list(W = c("W1","W2"), A = "A", "J" = "J", weights = "weights")
  output1 <- survivalThresh(data, weights = "weights", covariates = node_list$W, cutoffs_A = cutoffs_A, cutoffs_J = cutoffs_J, target_times = target_times, ngrid_A = 20, lrnr = Lrnr_hal9001$new(max_degree = 2, num_knots = c(10,5), smoothness_orders = 1, squash = TRUE, p_reserve = 0.95) , lrnr_A =    Lrnr_hal9001$new(max_degree = 2, num_knots = c(15,5), smoothness_orders = 1, squash = TRUE, p_reserve = 0.95),
                            max_eps =1e-1, split_by_J = T, max_iter = 100, fast_analysis = T, n_full_sample = 3000)
  
  est <- output1$estimates$`t=7`[[1]]$psi
  radius <- 1.96*sd(c(rep(0, 1000),output1$estimates$`t=7`[[1]]$EIC))/sqrt(nrow(data_full))
  estimates[[i]] <- c(est, est-radius, est + radius)
  outcome <- c(outcome, (true <=  est + radius) *(est - radius <= true))
  
  print(estimates[[i]])
  print(table(outcome))
  mean(outcome)
  #})
}


```


```{r}
data_sim <- as.data.table(simulate(100000, censoring = F))
true <- mean((data_sim$T <=7)*(data_sim$A >= cutoffs_A)*(data_sim$J >= cutoffs_J))/mean(data_sim$A >= cutoffs_A)
```









```{r}
library(hal9001)
data <- as.data.table(simulate(1000, censoring = F))
data
task <- sl3_Task$new(data, covariates = c("W1", "W2", "A"), outcome = "Ttilde", outcome_type = "continuous")

lrnr <- Lrnr_hal9001$new(num_knots = list(c(3,7,7)), max_degree = 1 , squash = F, smoothness_orders = 1, formula ="Ttilde~.")
lrnr <- lrnr$train(task)
lrnr$fit_object$basis_list
```







